markdown:               redcarpet
pygments:               true

permalink:              /:year/:month/:title.html

name:                   Developers that rocks
title:                  Developers that rocks
url:                    http://developer.vtmer.com

authors:
    hbc:
        name: hbc
        github: bcho
